### ISSUE TITLE
Not working on Android 14 (Jan Release)

### ISSUE THREAD

**Issue by Cr0vis** [lonelytransistor/SystemUINotifier#1]
Probably as expected but thought I would leave this here anyways as this seems to be the only application that relocates icons on the status bar. Using in conjunction with Pixel Xpert, could be a problem.
![Screenshot_20240302-102413](https://github.com/lonelytransistor/SystemUINotifier/assets/99766020/fc10195a-6da4-459d-b127-7828b557d886)

**Comment by lonelytransistor** [comment]
Android 13 changed key class, so already it won't work. Maybe I'll update my phone finally to 13, so it will work. However since I'm on Note 9, I cannot use PixelExpert. Could you tell me what could clash in it with my module?

**Comment by lonelytransistor** [comment]
Android 13 changed key class, so already it won't work. Maybe I'll update my phone finally to 13 in the nearest future, so I can work on it. However since I'm on Note 9, I cannot use PixelExpert. Could you tell me what could clash in it with my module?

**Comment by Cr0vis** [comment]
Pixel Xpert has some status bar tweaks that could interfere with padding like multi-row notification/system icons and the network monitor etc. Not no developer so take my ideas with a grain of salt. Don't feel pressured to update just lookin for cool modules and thought I'd leave some feedback :)

**Comment by lonelytransistor** [comment]
Seems you are partially correct. I'm not 100% sure, but the modules may clash in a sense that you won't be able to use some of the statusbar icon slots. The workaround is: use different slots guessed via trial and error. I am however hooking the methods that PixelExpert uses to modify the statusbar, so maybe it'll be fine. I'd say wontfixletssee. But the Android 14 support is coming, no worries there.

**Comment by lonelytransistor** [comment]
I'm sorry, but no matter what I try, I cannot access any private methods on the newest Android 14. I'm afraid this is somehow related to LSPosed being out of date for this version of Android. I can't fix this.

**Comment by Cr0vis** [comment]
Which preview build are you on? I believe a lot of stuff is broken on the latest stuff, January's preview might work

**Comment by lonelytransistor** [comment]
I'm not quite sure. I simply downloaded via the Android Studio an image for the emulator. How do I check it? It says in the about section:
Android version: 14
Android security update: September 5, 2023

I don't know where to ask, so any suggestions are welcome. XDA seems dead, seems to me like the days of hacking your phones are so past their prime that they are nearing extinction.

I tried to access the `method_` field in the C++ Java Class definition via `sun.misc.Unsafe` and indeed, there is nothing except public methods there, and sometimes not even all of them. But how does the JVM call the methods then? Fixing this requires such intricate knowledge of Java, which I think only the guys from LSPosed and similar possess.

**Comment by lonelytransistor** [comment]
Honestly, this version of Android seems broken like hell. Or rather XPosed on it.
Can you try the new prerelease and tell me what's broken (look at logcat)?

**Comment by Cr0vis** [comment]
Sorry, I have zero knowledge when it comes to coding languages, and compiling an APK from your source is past my forte. Maybe asking around in Mahmud0808 [telegram/GitHub](https://github.com/Mahmud0808/Iconify) is your best bet as he's doing a lot of the same stuff. There's also some interesting stuff on the [iconify GitHub ](https://github.com/Mahmud0808/Iconify/discussions/394#discussioncomment-7977395) that could relate

**Comment by lonelytransistor** [comment]
No compilation needed, I made for you a pre-release here yesterday 
https://github.com/lonelytransistor/SystemUINotifier/releases/download/v1.4rc1/SystemUI.Notifier.v1.4rc1.apk
Please let me know if it works and if not what errors you get in logcat if you can.

And thank you for the link. Sadly it seems they're having the same issue.

EDIT: For the posterity and future me. Everything in the code is ok. However, Google uses some sort of optimization for their apks. The code inside the apk is NOT the same as the one in .java from their source code. Instead, the functions get inlined where possible. What you would need is to recompile the files from code and use them as a drop in replacement. But then no proper signature. And in case of closed source OS like OneUI or MIUI it's just impossible. In short: only custom ROMs may work with XPosed in the future.

**Comment by Cr0vis** [comment]
Not working, no changes when a slot is selected. Seems you fixed the crash that happens when searching for an app though.
Are you talking about the lsposed modules log?  

net.lonelytransistor.notificationinsystem from /data/app/~~DfoYOcFsVYEaL9TCtBNQhw==/net.lonelytransistor.notificationinsystem-lMTTcwYdH_ICCVae7p9ACQ==/base.apk
[ 2024-03-10T08:21:15.124    10608: 23835: 23835 I/LSPosed-Bridge  ]   Loading class net.lonelytransistor.notificationinsystem.hooks.XPosedHook
[ 2024-03-10T08:21:15.124    10608: 23835: 23835 I/LSPosed-Bridge  ]   Loading class net.lonelytransistor.notificationinsystem.hooks.XPosedZygote
[ 2024-03-10T08:21:15.125    10608: 23835: 23835 E/LSPosed-Bridge  ]     Failed to load class net.lonelytransistor.notificationinsystem.hooks.XPosedZygote
java.lang.ClassNotFoundException: Didn't find class "net.lonelytransistor.notificationinsystem.hooks.XPosedZygote" on path: DexPathList[[dex file "InMemoryDexFile[cookie=[0, -5476376661314908400]]"],nativeLibraryDirectories=[/data/app/~~DfoYOcFsVYEaL9TCtBNQhw==/net.lonelytransistor.notificationinsystem-lMTTcwYdH_ICCVae7p9ACQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at l0.loadClass(Unknown Source:18)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at z.o.pVx.qN.AkUWka.O.Fw.XposedInit.initModule(Unknown Source:40)
	at z.o.pVx.qN.AkUWka.O.Fw.XposedInit.loadModule(Unknown Source:144)
	at z.o.pVx.qN.AkUWka.O.Fw.XposedInit.lambda$loadLegacyModules$0(Unknown Source:15)
	at z.o.pVx.qN.AkUWka.O.Fw.XposedInit.b(Unknown Source:0)
	at O0.accept(Unknown Source:8)
	at java.util.ArrayList.forEach(ArrayList.java:1528)
	at z.o.pVx.qN.AkUWka.O.Fw.XposedInit.loadLegacyModules(Unknown Source:12)
	at YAdkRA.V.ERrFiq.KqOiP.Main.forkCommon(Unknown Source:235)
	at com.android.internal.os.Zygote.nativeSpecializeAppProcess(Native Method)
	at com.android.internal.os.Zygote.specializeAppProcess(Zygote.java:430)
	at com.android.internal.os.Zygote.childMain(Zygote.java:864)
	at com.android.internal.os.Zygote.forkSimpleApps(Zygote.java:724)
	at com.android.internal.os.ZygoteConnection.processCommand(ZygoteConnection.java:287)
	at com.android.internal.os.ZygoteServer.runSelectLoop(ZygoteServer.java:521)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by lonelytransistor** [comment]
This one is normal, I just couldn't be bothered to fix it.
The module saves its settings and refreshes the statusbar when you exit the configuration app.
So let's try something simple:
1. Open configurator
2. Look for your messages app
3. Enable hook for all its categories
4. Press back/save button
5. Send yourself an SMS
Then remove the notification and then send me the log from LSPosed.

**Comment by Cr0vis** [comment]
Here ya go ![LSPosed_2024-03-10T08_25_03.990081.zip](https://github.com/lonelytransistor/SystemUINotifier/files/14550224/LSPosed_2024-03-10T08_25_03.990081.zip)

**Comment by lonelytransistor** [comment]
Just to make a sanity check here, you did restart either the phone or SystemUI via the "Restart SystemUI" option in ClassicPowerMenu or similar after updating my module? And well obviously enabled it for SystemUI before that.

If yes then idk, it seems like my module is either not loading or being overriden by some other.

I'll add verbosity to the module later, because right now it tells me nothing, which in hindsight is not that good.

**Comment by Cr0vis** [comment]
Yeah, guess this is going to be a doozy to figure out. I'll be lurking around in-between updates to provide more feedback if needed :)

**Comment by lonelytransistor** [comment]
Sadly I have no idea where to look even. It looks exactly if the module wasn't activated in LSPosed. So why it's completely unloaded is a mystery to me.
I've created a debug version with some verbosity, could be helpful. If you have the time try it out and send me the logs along with maybe your SystemUI.apk:
https://github.com/lonelytransistor/SystemUINotifier/releases/download/v1.4rc1/app-debug.apk

**Comment by lonelytransistor** [comment]
Sadly I have no idea where to look even. It looks exactly as if the module wasn't activated in LSPosed. So why it's completely not loaded is a mystery to me. You would at least get an error or a crash.

I've created a debug version with some verbosity, could be helpful. If you have the time try it out and send me the logs along with maybe your SystemUI.apk:
https://github.com/lonelytransistor/SystemUINotifier/releases/download/v1.4rc1/app-debug.apk

**Comment by Cr0vis** [comment]
![LSPosed_2024-03-10T12_56_40.837354.zip](https://github.com/lonelytransistor/SystemUINotifier/files/14551106/LSPosed_2024-03-10T12_56_40.837354.zip)

![SystemUIGoogle.apk.zip](https://github.com/lonelytransistor/SystemUINotifier/files/14551131/SystemUIGoogle.apk.zip)

**Comment by lonelytransistor** [comment]
Please activate the module for com.android.systemui and reboot your phone. The logs indicate that you are not doing that.

**Comment by lonelytransistor** [comment]
You know what? I give up. Screw this, everything is different from the source code. Sorry. Just stay at Android12 or use other manufacturers, ones that actually don't do things to spite the user.

I'm leaving you one final release and I give up:
https://github.com/lonelytransistor/SystemUINotifier/releases/download/v1.4rc2/app-debug.apk
